# vim:ft=kitty

## name: Aura Dracula Spirit (Soft)
## author: JoseMurilloc (adapted for kitty)
## license: MIT
## upstream: https://github.com/JoseMurilloc/aura-spirit-dracula
## blurb: Purple-forward dark theme — unified across kitty + tmux + nvim


#: The basic colors

foreground #edecee
background #191521
selection_foreground none
selection_background #3d375e


#: Cursor colors

cursor #a277ff
cursor_text_color #191521


#: URL underline color when hovering with mouse

url_color #82e2ff


#: kitty window border colors and terminal bell colors

active_border_color #a277ff
inactive_border_color #2e2b38
bell_border_color #ffca85
visual_bell_color none


#: OS Window titlebar colors

wayland_titlebar_color #14111b
macos_titlebar_color #14111b


#: Tab bar colors

active_tab_foreground #edecee
active_tab_background #191521
inactive_tab_foreground #64548E
inactive_tab_background #14111b
tab_bar_background #14111b
tab_bar_margin_color none


#: Colors for marks (marked text in the terminal)

mark1_foreground #191521
mark1_background #a277ff
mark2_foreground #191521
mark2_background #61ffca
mark3_foreground #191521
mark3_background #f694ff


#: The basic 16 colors

#: black
color0 #14111b
color8 #64548E

#: red
color1 #ff6767
color9 #ff6767

#: green
color2 #61ffca
color10 #61ffca

#: yellow
color3 #ffca85
color11 #ffca85

#: blue
color4 #a277ff
color12 #a277ff

#: magenta
color5 #f694ff
color13 #f694ff

#: cyan
color6 #82e2ff
color14 #82e2ff

#: white
color7 #edecee
color15 #ffffff
